name: build game

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

on:
  workflow_dispatch:
    inputs:
      game:
        description: 'Game to build binaries for'
        required: true
        type: choice
        options:
          - 'basic'
          - 'cube-spawner'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Build
        run: cargo build --bin ${{ inputs.game }} --release

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.game }}-windows
          path: target/release/${{ inputs.game }}.exe